TokenSharp
TokenSpace
TokenDollar
KeywordWithFile(Source)
TokenSpace
FilePath(/my/perl/script/kwextract.pl)
TokenVee
TokenDollar
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithDate(Date)
TokenSpace
DateValue(now)
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithFile(mutable)
TokenSpace
FilePath(/.brings/system/bin/kwextract.pl)
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithQmHash(previous)
TokenSpace
QmHash(QmU1RDLsAGNPVuwDjKD3RQx7R6aEuQfcmSiubviDZ2XRVC)
TokenEndOfLine
TokenEmptyLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithQmHash(parents)
TokenSpace
QmHash(QmRU26t5KP5QLiNbjWMxSbyfaARvzshfdzozj6M4K73auH)
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithZ2Hash(qm)
TokenSpace
Z2Hash(z2kXGab6zthT87F8zfEci4Ah7ngKD9VNjagPTHxVnSGzugX)
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithInteger(tic)
Tic(1579373044)
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithInteger(spot)
Spot(1550698403)
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithString(Signature)
Signature(n/a)
TokenEndOfLine
TokenEmptyLine
TokenEndOfLine
TextWordConstant(line)
TextWordConstant(1)
TokenEndOfLine
TextWordConstant(line)
TextWordConstant(2)
TextWordConstant(with)
TextWordConstant(a)
TokenDollar
TextVariableSubstituable(variable)
TokenDollar
TextWordConstant(embedded)
TokenEndOfLine
TextWordConstant(line)
TextWordConstant(3)
TokenEndOfLine
TokenEmptyLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithPersonName(Author)
AuthorName(michel)
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithString(next)
NextName(unknown)
TokenEndOfLine
TokenEmptyLine
TokenEndOfLine
TokenEmptyLine
TokenEndOfLine
