TokenSharp
TokenSpace
TokenDollar
KeywordWithFile(Source)
TokenSpace
FilePath(/my/perl/script/kwextract.pl)
TokenVee
TokenDollar
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithString(members)
TokenSharp
TokenSpace
TokenDollar
KeywordWithDate(Date)
TokenSpace
DateValue(27-09-1998)
TokenEndOfLine
TokenSpace
TokenEndOfLine
