TokenSharp
TokenSpace
TokenDollar
KeywordWithDate(Date)
TokenColon
TokenSpace
DateValue(27-07-1998)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithInteger(tic)
TokenColon
TokenSpace
Tic(1579373044)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithFile(mutable)
TokenColon
TokenSpace
FilePath(/.brings/system/bin/kwextract.pl)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithQmHash(previous)
TokenColon
TokenSpace
QmHash(QmU1RDLsAGNPVuwDjKD3RQx7R6aEuQfcmSiubviDZ2XRVC)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithFile(Source)
TokenColon
TokenSpace
FilePath(/my/perl/script/kwextract.pl)
TokenComma
TokenVee
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithPersonName(Author)
TokenColon
TokenSpace
AuthorName(michelc@lausanne)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithString(members)
TokenSpace
AuthorName(michel@ocean)
TokenSpace
TokenComma
TokenSpace
AuthorName(emile@paris13)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithString(next)
TokenColon
TokenSpace
NextName(unknown)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithInteger(spot)
TokenColon
Spot(1550698403)
TokenDollar
TokenEndOfLine
TokenEndOfLine
