TokenSharp
TokenSpace
TokenDollar
KeywordWithFile(Source)
TokenColon
TokenSpace
FilePath(/my/perl/script/kwextract.pl)
TokenComma
TokenVee
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithDate(Date)
TokenColon
TokenSpace
DateValue(30-03-1997)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithFile(mutable)
TokenColon
TokenSpace
FilePath(/.brings/system/bin/kwextract.pl)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithInteger(tic)
TokenColon
TokenSpace
Tic(1579373044)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithInteger(spot)
TokenColon
Spot(1550698403)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenEndOfLine
TextWordConstant(line)
TokenSpace
TextWordConstant(1)
TokenSpace
TextWordConstant(this)
TokenSpace
TextWordConstant(is)
TokenSpace
TextWordConstant(a)
TokenSpace
TextWordConstant(genesis)
TokenSpace
TextWordConstant(block)
TokenEndOfLine
TextWordConstant(line)
TokenSpace
TextWordConstant(2)
TokenSpace
TextWordConstant(with)
TokenSpace
TextWordConstant(a)
TokenSpace
TokenDollar
TextWordConstant(variable)
TokenDollar
TokenSpace
TextWordConstant(embedded)
TokenEndOfLine
TextWordConstant(line)
TokenSpace
TextWordConstant(3)
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithPersonName(Author)
TokenColon
TokenSpace
AuthorName(michel)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenSharp
TokenSpace
TokenDollar
KeywordWithString(next)
TokenColon
TokenSpace
NextName(unknown)
TokenDollar
TokenEndOfLine
TokenEndOfLine
TokenEndOfLine
TokenSpace
TokenEndOfLine
