TokenSharp
TokenSpace
TokenDollar
KeywordWithString(Signature)
Signature(n/a)
TokenEndOfLine
TokenEmptyLine
TokenEndOfLine
TextWordConstant(line)
TextWordConstant(1)
TokenEndOfLine
TextWordConstant(line)
TextWordConstant(2)
TextWordConstant(with)
TextWordConstant(a)
TokenDollar
TextVariableSubstituable(variable)
TokenDollar
TextWordConstant(embedded)
TokenEndOfLine
TextWordConstant(line)
TextWordConstant(3)
TokenEndOfLine
TokenEmptyLine
TokenEndOfLine
TokenEmptyLine
TokenEndOfLine
